### ISSUE TITLE
Could you add another option Forwarding Host/API Host?

### ISSUE THREAD

**Issue by StrollStars** [ikuma-hiroyuki/ExcelChatGPT#1]
Could you add another option Forwarding Host/API Host for adding my custom host for my custom api key?
BTW, hope to be able to provide xlam file.

**Comment by ikuma-hiroyuki** [comment]
Hi!

I am an inexperienced developer and would like to fulfill your request, but I don't understand it well.

What does "Could you add another option Forwarding Host/API Host for adding my custom host for my custom api key?"

**Comment by StrollStars** [comment]
@ikuma-hiroyuki Usually the OpenAI API Host is https://api.openai.com, but I want to change it to my own server. How should I do this?

**Comment by ikuma-hiroyuki** [comment]
@StrollStars Hmmm. I don't know. Sorry.

**Comment by StrollStars** [comment]
@ikuma-hiroyuki Thank you all the same.
